"""initial

Revision ID: 0001
Revises: 
Create Date: 2026-05-31 16:31:33.793021
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # --- manual: required extensions BEFORE any vector column / pg_trgm index ---
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('source_system', sa.Text(), nullable=False),
    sa.Column('connector', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('cursor', sa.Text(), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_runs'))
    )
    op.create_table('ontology_node_types',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('properties_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_ontology_node_types'))
    )
    op.create_table('ontology_relationship_types',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('allowed_source_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('allowed_target_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_symmetric', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_ontology_relationship_types'))
    )
    op.create_table('raw_documents',
    sa.Column('source_system', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('source_created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('source_updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_documents')),
    sa.UniqueConstraint('source_system', 'source_type', 'external_id', name='uq_raw_documents_identity')
    )
    op.create_index('ix_raw_documents_source', 'raw_documents', ['source_system', 'source_type'], unique=False)
    op.create_table('nodes',
    sa.Column('node_type', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('source_system', sa.Text(), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('canonical_node_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Float(), server_default=sa.text('1.0'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_node_id'], ['nodes.id'], name=op.f('fk_nodes_canonical_node_id_nodes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['node_type'], ['ontology_node_types.name'], name=op.f('fk_nodes_node_type_ontology_node_types'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nodes')),
    sa.UniqueConstraint('node_type', 'source_system', 'external_id', name='uq_nodes_identity')
    )
    op.create_index('ix_nodes_node_type', 'nodes', ['node_type'], unique=False)
    op.create_index('ix_nodes_properties', 'nodes', ['properties'], unique=False, postgresql_using='gin')
    op.create_index('ix_nodes_source', 'nodes', ['source_system', 'external_id'], unique=False)
    # --- manual: pgvector HNSW (cosine) + pg_trgm indexes. Their operator classes
    # and index options aren't faithfully round-tripped by autogenerate, so they're
    # excluded via include_object in env.py and created explicitly here. ---
    op.create_index(
        'ix_nodes_embedding_hnsw', 'nodes', ['embedding'], unique=False,
        postgresql_using='hnsw',
        postgresql_with={'m': 16, 'ef_construction': 64},
        postgresql_ops={'embedding': 'vector_cosine_ops'},
    )
    op.create_index(
        'ix_nodes_name_trgm', 'nodes', ['name'], unique=False,
        postgresql_using='gin',
        postgresql_ops={'name': 'gin_trgm_ops'},
    )
    op.create_table('edges',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('relationship', sa.Text(), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('weight', sa.Float(), server_default=sa.text('1.0'), nullable=False),
    sa.Column('confidence', sa.Float(), server_default=sa.text('1.0'), nullable=False),
    sa.Column('evidence_document_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_document_id'], ['raw_documents.id'], name=op.f('fk_edges_evidence_document_id_raw_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['relationship'], ['ontology_relationship_types.name'], name=op.f('fk_edges_relationship_ontology_relationship_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['nodes.id'], name=op.f('fk_edges_source_id_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['nodes.id'], name=op.f('fk_edges_target_id_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_edges')),
    sa.UniqueConstraint('source_id', 'target_id', 'relationship', name='uq_edges_identity')
    )
    op.create_index('ix_edges_properties', 'edges', ['properties'], unique=False, postgresql_using='gin')
    op.create_index('ix_edges_relationship', 'edges', ['relationship'], unique=False)
    op.create_index('ix_edges_source_id', 'edges', ['source_id'], unique=False)
    op.create_index('ix_edges_target_id', 'edges', ['target_id'], unique=False)
    op.create_table('node_mentions',
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['raw_documents.id'], name=op.f('fk_node_mentions_document_id_raw_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], name=op.f('fk_node_mentions_node_id_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_node_mentions')),
    sa.UniqueConstraint('node_id', 'document_id', name='uq_node_mentions_identity')
    )
    op.create_index('ix_node_mentions_document_id', 'node_mentions', ['document_id'], unique=False)
    op.create_index('ix_node_mentions_node_id', 'node_mentions', ['node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_node_mentions_node_id', table_name='node_mentions')
    op.drop_index('ix_node_mentions_document_id', table_name='node_mentions')
    op.drop_table('node_mentions')
    op.drop_index('ix_edges_target_id', table_name='edges')
    op.drop_index('ix_edges_source_id', table_name='edges')
    op.drop_index('ix_edges_relationship', table_name='edges')
    op.drop_index('ix_edges_properties', table_name='edges', postgresql_using='gin')
    op.drop_table('edges')
    op.drop_index('ix_nodes_name_trgm', table_name='nodes', postgresql_using='gin')
    op.drop_index('ix_nodes_embedding_hnsw', table_name='nodes', postgresql_using='hnsw')
    op.drop_index('ix_nodes_source', table_name='nodes')
    op.drop_index('ix_nodes_properties', table_name='nodes', postgresql_using='gin')
    op.drop_index('ix_nodes_node_type', table_name='nodes')
    op.drop_table('nodes')
    op.drop_index('ix_raw_documents_source', table_name='raw_documents')
    op.drop_table('raw_documents')
    op.drop_table('ontology_relationship_types')
    op.drop_table('ontology_node_types')
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
    # Note: the `vector` / `pg_trgm` extensions are intentionally NOT dropped —
    # other databases/objects in the cluster may depend on them.
