"""resource_key + audit + grants

Revision ID: 0002
Revises: 0001
Create Date: 2026-05-31 18:07:55.864728
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_grants',
    sa.Column('group_name', sa.Text(), nullable=False),
    sa.Column('source_system', sa.Text(), nullable=False),
    sa.Column('resource_key', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_grants')),
    sa.UniqueConstraint('group_name', 'source_system', 'resource_key', name='uq_access_grants_identity')
    )
    op.create_index('ix_access_grants_group', 'access_grants', ['group_name'], unique=False)
    op.create_table('audit_log',
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('groups', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool', sa.Text(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_node_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_log_subject', 'audit_log', ['subject'], unique=False)
    op.create_index('ix_audit_log_tool', 'audit_log', ['tool'], unique=False)
    op.add_column('raw_documents', sa.Column('resource_key', sa.Text(), nullable=True))
    op.create_index('ix_raw_documents_resource', 'raw_documents', ['source_system', 'resource_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_raw_documents_resource', table_name='raw_documents')
    op.drop_column('raw_documents', 'resource_key')
    op.drop_index('ix_audit_log_tool', table_name='audit_log')
    op.drop_index('ix_audit_log_subject', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_access_grants_group', table_name='access_grants')
    op.drop_table('access_grants')
    # ### end Alembic commands ###
